Console.CursorVisible = false;
Console.WriteLine("Task in progress...");
Console.BackgroundColor = ConsoleColor.White;
int timeout = 200;
Console.Write(" ");
Thread.Sleep(timeout);
Console.Write(" ");
Thread.Sleep(timeout);
Console.Write(" ");
Thread.Sleep(timeout);
Console.Write(" "); 
Thread.Sleep(timeout);
Console.Write(" ");
Thread.Sleep(timeout);
Console.Write(" ");
Thread.Sleep(timeout);
Console.Write(" "); 
Thread.Sleep(timeout);
Console.Write(" ");
Thread.Sleep(timeout);
Console.Write(" ");
Thread.Sleep(timeout);
Console.Write(" ");
Thread.Sleep(timeout);
Console.Write(" ");
Thread.Sleep(timeout);
Console.Write(" ");
Thread.Sleep(timeout);
Console.Write(" ");
Thread.Sleep(timeout);
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.Black;

int time = 20;
string result = (time < 18) ? "Good day" : "Good evening";
Console.WriteLine(result);